### PR TITLE
16 user routes fix

### PR DESCRIPTION
**Pull request by JustDaile**
- Fixed and refactored user routes.
   - Improved error handling of the user routes.
- Added reusable model struct.
   - Added lifecycle hooks for models.
- Included some basic unit tests.
- Added vscode configuration for debugging.
- Changed how/when passwords are hashed.

### CODE REVIEW

**Comment by JustDaile** [comment]
My apologies on the wide scope of this PR.

**Review by ghost — COMMENTED** [review]
Looks good ,  just few things , 

`HandleCreateUser` is using `json.NewDecoder`  , please use the `ReadJson` utility 

`HandleCreateUser` and `HandleUpdateUserById` need to validate the request payload , use the validator utility for the same - `utils.Validator.Struct(<your dto struct>)` 
refer to `HandleSignUp` handler for quick reference, the dtos need custom `validate` tag

**Comment by JustDaile** [comment]
Later commits do use the utils. I fixed it later on, please check.

**Review by ghost — APPROVED** [review]
lgtm

**Pull request merged**
